# Generated by Django 3.1.5 on 2021-01-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('rank', models.CharField(max_length=50, verbose_name='Ранг')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('race', models.CharField(max_length=50, verbose_name='Раса')),
                ('uniqueness', models.TextField(verbose_name='Уникальность')),
            ],
        ),
    ]
