# Generated by Django 3.1.5 on 2021-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroes',
            options={'verbose_name': 'Герой', 'verbose_name_plural': 'Герои'},
        ),
        migrations.AddField(
            model_name='heroes',
            name='icon',
            field=models.TextField(default='https://static.wikia.nocookie.net/7dsgc_mobile_game/images/4/4a/Icon_stamp_escanor_01.png/revision/latest/scale-to-width-down/340?cb=20200607192821', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='color',
            field=models.CharField(choices=[('1', 'Зеленый'), ('2', 'Красный'), ('3', 'Синий')], max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='race',
            field=models.CharField(choices=[('1', 'Богиня'), ('2', 'Великан'), ('3', 'Демон'), ('4', 'Неизвестно'), ('5', 'Фея'), ('6', 'Человек')], max_length=10, verbose_name='Раса'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='rank',
            field=models.CharField(choices=[('1', 'SSR'), ('2', 'SR'), ('3', 'R')], max_length=3, verbose_name='Ранг'),
        ),
    ]
