# Generated by Django 3.1.5 on 2021-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210129_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Иконка'),
        ),
    ]
