# Generated by Django 3.1.5 on 2021-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210129_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='color',
            field=models.CharField(choices=[('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Синий', 'Синий')], max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='icon',
            field=models.CharField(max_length=200, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='race',
            field=models.CharField(choices=[('Богиня', 'Богиня'), ('Великан', 'Великан'), ('Демон', 'Демон'), ('Неизвестно', 'Неизвестно'), ('Фея', 'Фея'), ('Человек', 'Человек')], max_length=10, verbose_name='Раса'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='rank',
            field=models.CharField(choices=[('SSR', 'SSR'), ('SR', 'SR'), ('R', 'R')], max_length=3, verbose_name='Ранг'),
        ),
    ]
