# Generated by Django 3.1.5 on 2021-01-29 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210129_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='date_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
