# Generated by Django 3.1.5 on 2021-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_heroes_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroes',
            name='properties',
        ),
        migrations.AlterField(
            model_name='heroes',
            name='color',
            field=models.CharField(choices=[(None, 'Выберите цвет'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Синий', 'Синий')], max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='icon',
            field=models.URLField(verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='race',
            field=models.CharField(choices=[(None, 'Выберите расу'), ('Богиня', 'Богиня'), ('Великан', 'Великан'), ('Демон', 'Демон'), ('Неизвестно', 'Неизвестно'), ('Фея', 'Фея'), ('Человек', 'Человек')], max_length=10, verbose_name='Раса'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='rank',
            field=models.CharField(choices=[(None, 'Выберите ранг'), ('SSR', 'SSR'), ('SR', 'SR'), ('R', 'R')], max_length=3, verbose_name='Ранг'),
        ),
    ]
