# Generated by Django 3.1.5 on 2021-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210130_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='ignition',
            field=models.NullBooleanField(verbose_name='Воспламенение'),
        ),
        migrations.AddField(
            model_name='heroes',
            name='weakness',
            field=models.NullBooleanField(verbose_name='Слабое место'),
        ),
    ]
