# Generated by Django 3.1.5 on 2021-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210130_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroes',
            name='ignition',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='weakness',
        ),
        migrations.AddField(
            model_name='heroes',
            name='properties',
            field=models.TextField(blank=True, verbose_name='Свойства'),
        ),
    ]
