# Generated by Django 3.1.5 on 2021-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210201_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
