# Generated by Django 3.1.5 on 2021-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210210_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, to='main.Properties', verbose_name='Свойства'),
        ),
    ]
