# Generated by Django 3.1.5 on 2021-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210211_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='properties',
            field=models.ManyToManyField(blank=True, to='main.Properties', verbose_name='Свойства'),
        ),
    ]
