# Generated by Django 3.1.5 on 2021-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210211_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='icon',
            field=models.URLField(unique=True, verbose_name='Иконка'),
        ),
    ]
